### PR TITLE
Update state_class for import / export entities

### PR DESCRIPTION
**Pull request by klaasnicolaas**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
The adjustments in this pull request ensure that the `state_class` is correct and the entities work properly again in the energy dashboard.

* **What is the current behavior?** (You can also link to an open issue here)
Users get an error message in the energy dashboard

* **What is the new behavior (if this is a feature change)?**
The import and export entities have the correct state_class again

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Nope

* **Other information**:
image

### CODE REVIEW

**Comment by DCSBL** [comment]
Thank you for your time! This change is already added in https://github.com/DCSBL/ha-homewizard-energy/pull/51 and rolled out in 0.10.0.

**Comment by klaasnicolaas** [comment]
Strange, I overlooked that change because the PR title was about gas. But glad it's resolved 😄

**Comment by DCSBL** [comment]
Yeah that is something that was not quite clear. I've updated the release notes. Anyway, thanks for the heads-up!

**Comment by klaasnicolaas** [comment]
A little tip, keep pull requests small and to the point as the title stands for. Is easier with reviews and changes are findable for those who want to contribute. (We also use this in the core repository of Home Assistant) 😉 But otherwise great work and keep it up!

**Comment by DCSBL** [comment]
Thanks!
Just a quick question; I like to have this integration in Core. Is it just 'make it good (Unit tests, linting, followed guidelines etc.) and open a PR' or are there other steps to follow? 

_As this is not the right place for these kinds of things, you also may reach out at Discord (DCSBL#2823)_

**Comment by klaasnicolaas** [comment]
@DCSBL I think you had another question here, something about bringing integration to core. If you need help you can always contact me on Discord (Mister Nicolaz#7558) 😉

**Pull request closed without merging**
